\" obus-introspect.1
\" -----------------
\" Copyright : (c) 2009, Jeremie Dimino <jeremie@dimino.org>
\" Licence   : BSD3
\"
\" This file is a part of obus, an ocaml implementation of D-Bus.

.TH OBUS-INTROSPECT 1 "October 2009"

.SH NAME
obus-introspect \- a D-Bus introspecter

.SH SYNOPSIS
.B obus-intrpsoect
[
.I options
]
.I destination
.I path

.SH DESCRIPTION

.B obus-introspect
allow you to introspect a D-Bus service. Given a
.B path
it can introspect recursively all its children. By default it prints
only all the interfaces it found, but it can also prints all object
path with the interfaces they implements.

.SH OPTIONS

.IP -rec
Introspects recursively all sub-nodes instead of just the one of
.B path
.I path

.IP -session
The service is on the session bus (the default).

.IP -system
The service is on the system bus.

.IP -objects
List objects with interfaces they implements instead of interfaces.

.IP "-help or --help"
Display a short usage summary and exit.

.SH AUTHOR
Jérémie Dimino <jeremie@dimino.org>

.SH "SEE ALSO"
.BR obus-dump (1),
.BR obus-binder (1).
