(*
 * bus.mli
 * -------
 * Copyright : (c) 2008, Jeremie Dimino <jeremie@dimino.org>
 * Licence   : BSD3
 *
 * This file is a part of obus, an ocaml implemtation of dbus.
 *)

(** Internal lib, used by autogenerated code *)

exception Connection_failure of string
exception Communication_error
exception Data_error of string

type bus

val connect : Address.t list -> bus
