(*
 * marshaler.mli
 * -------------
 * Copyright : (c) 2008, Jeremie Dimino <jeremie@dimino.org>
 * Licence   : BSD3
 *
 * This file is a part of obus, an ocaml implemtation of dbus.
 *)

(** Used by autogenerated interfaces *)

type ptr = int
    (** A position in a buffer *)

type buffer = string
    (** A buffer containing a marshaled value *)

exception Write_error of string
exception Read_error of string

module type Basic = sig
  (** Basic reading/writing functions whose depends on byte order *)
  type 'a t
  val buffer : buffer
  val pad2 : ptr -> ptr
  val pad4 : ptr -> ptr
  val pad8 : ptr -> ptr
  val bool_boolean : bool t
  val int_int16 : int t
  val int_int32 : int t
  val int_int64 : int t
  val int_uint16 : int t
  val int_uint32 : int t
  val int_uint64 : int t
  val int32_int32 : int32 t
  val int64_int64 : int64 t
  val int32_uint32 : int32 t
  val int64_uint64 : int64 t
  val float_double : float t
end

module type BasicWriter = Basic with type 'a t = ptr -> 'a -> unit
module type BasicReader = Basic with type 'a t = ptr -> 'a

module type Buffer = sig
  val buffer : buffer
end

module LEWriter(B : Buffer) : BasicWriter
module BEWriter(B : Buffer) : BasicWriter

module LEReader(B : Buffer) : BasicReader
module BEReader(B : Buffer) : BasicReader

module SingleWriter(B : BasicWriter) : sig
  val write_single_t : ptr -> Types_internal.single -> ptr
  val write_t : ptr -> Types_internal.t -> ptr
  val write_single_v : ptr -> Values_internal.single -> ptr
  val write_v : ptr -> Values_internal.t -> ptr
end

module SingleReader(B : BasicReader) : sig
  val read_single_t : ptr -> ptr * Types_internal.single
  val read_t : ptr -> ptr * Types_internal.t
  val read_single_v : ptr -> Types_internal.single -> ptr * Values_internal.single
  val read_v : ptr -> Types_internal.t -> ptr * Values_internal.t
end
