(* File auto-generated by obus_gen_interface.best, DO NOT EDIT. *)
open OBus_value
open OBus_value.C
open OBus_member
open OBus_object
module Org_freedesktop_Notifications =
struct
  let interface = "org.freedesktop.Notifications"
  let m_GetServerInformation = {
    Method.interface = interface;
    Method.member = "GetServerInformation";
    Method.i_args = (arg0);
    Method.o_args = (arg4
                       (Some "return_name", basic_string)
                       (Some "return_vendor", basic_string)
                       (Some "return_version", basic_string)
                       (Some "return_spec_version", basic_string));
  }
  let m_GetCapabilities = {
    Method.interface = interface;
    Method.member = "GetCapabilities";
    Method.i_args = (arg0);
    Method.o_args = (arg1
                       (Some "return_caps", array basic_string));
  }
  let m_CloseNotification = {
    Method.interface = interface;
    Method.member = "CloseNotification";
    Method.i_args = (arg1
                       (Some "id", basic_uint32));
    Method.o_args = (arg0);
  }
  let m_Notify = {
    Method.interface = interface;
    Method.member = "Notify";
    Method.i_args = (arg8
                       (Some "app_name", basic_string)
                       (Some "id", basic_uint32)
                       (Some "icon", basic_string)
                       (Some "summary", basic_string)
                       (Some "body", basic_string)
                       (Some "actions", array basic_string)
                       (Some "hints", dict string variant)
                       (Some "timeout", basic_int32));
    Method.o_args = (arg1
                       (Some "return_id", basic_uint32));
  }
  let make
      ?notify_mode
      ~m_GetServerInformation:m__GetServerInformation
      ~m_GetCapabilities:m__GetCapabilities
      ~m_CloseNotification:m__CloseNotification
      ~m_Notify:m__Notify
      ()
      =
    OBus_object.make_interface_unsafe ?notify_mode interface
      [|
        method_info m_GetServerInformation m__GetServerInformation;
        method_info m_GetCapabilities m__GetCapabilities;
        method_info m_CloseNotification m__CloseNotification;
        method_info m_Notify m__Notify;
      |]
      [|
      |]
      [|
      |]
end
