(* File auto-generated by obus_gen_interface.best, DO NOT EDIT. *)
open OBus_member
module Org_freedesktop_Notifications : sig
  val m_GetServerInformation : (unit, string * string * string * string) Method.t
  val m_GetCapabilities : (unit, string list) Method.t
  val m_CloseNotification : (int32, unit) Method.t
  val m_Notify : (string * int32 * string * string * string * string list * (string * OBus_value.V.single) list * int32, int32) Method.t
  val make :
    ?notify_mode : 'a OBus_object.notify_mode ->
    m_GetServerInformation : ((string * string * string * string) OBus_context.t -> 'a -> unit -> (string * string * string * string) Lwt.t) ->
    m_GetCapabilities : (string list OBus_context.t -> 'a -> unit -> string list Lwt.t) ->
    m_CloseNotification : (unit OBus_context.t -> 'a -> int32 -> unit Lwt.t) ->
    m_Notify : (int32 OBus_context.t -> 'a -> string * int32 * string * string * string * string list * (string * OBus_value.V.single) list * int32 -> int32 Lwt.t) ->
    unit -> 'a OBus_object.interface
end
