(* File auto-generated by obus_gen_interface.best, DO NOT EDIT. *)
open OBus_member
module Org_freedesktop_DBus : sig
  val m_Hello : (unit, string) Method.t
  val m_RequestName : (string * int32, int32) Method.t
  val m_ReleaseName : (string, int32) Method.t
  val m_StartServiceByName : (string * int32, int32) Method.t
  val m_UpdateActivationEnvironment : ((string * string) list, unit) Method.t
  val m_NameHasOwner : (string, bool) Method.t
  val m_ListNames : (unit, string list) Method.t
  val m_ListActivatableNames : (unit, string list) Method.t
  val m_AddMatch : (string, unit) Method.t
  val m_RemoveMatch : (string, unit) Method.t
  val m_GetNameOwner : (string, string) Method.t
  val m_ListQueuedOwners : (string, string list) Method.t
  val m_GetConnectionUnixUser : (string, int32) Method.t
  val m_GetConnectionUnixProcessID : (string, int32) Method.t
  val m_GetAdtAuditSessionData : (string, string) Method.t
  val m_GetConnectionSELinuxSecurityContext : (string, string) Method.t
  val m_ReloadConfig : (unit, unit) Method.t
  val m_GetId : (unit, string) Method.t
  val s_NameOwnerChanged : (string * string * string) Signal.t
  val s_NameLost : string Signal.t
  val s_NameAcquired : string Signal.t
  val make :
    ?notify_mode : 'a OBus_object.notify_mode ->
    m_Hello : (string OBus_context.t -> 'a -> unit -> string Lwt.t) ->
    m_RequestName : (int32 OBus_context.t -> 'a -> string * int32 -> int32 Lwt.t) ->
    m_ReleaseName : (int32 OBus_context.t -> 'a -> string -> int32 Lwt.t) ->
    m_StartServiceByName : (int32 OBus_context.t -> 'a -> string * int32 -> int32 Lwt.t) ->
    m_UpdateActivationEnvironment : (unit OBus_context.t -> 'a -> (string * string) list -> unit Lwt.t) ->
    m_NameHasOwner : (bool OBus_context.t -> 'a -> string -> bool Lwt.t) ->
    m_ListNames : (string list OBus_context.t -> 'a -> unit -> string list Lwt.t) ->
    m_ListActivatableNames : (string list OBus_context.t -> 'a -> unit -> string list Lwt.t) ->
    m_AddMatch : (unit OBus_context.t -> 'a -> string -> unit Lwt.t) ->
    m_RemoveMatch : (unit OBus_context.t -> 'a -> string -> unit Lwt.t) ->
    m_GetNameOwner : (string OBus_context.t -> 'a -> string -> string Lwt.t) ->
    m_ListQueuedOwners : (string list OBus_context.t -> 'a -> string -> string list Lwt.t) ->
    m_GetConnectionUnixUser : (int32 OBus_context.t -> 'a -> string -> int32 Lwt.t) ->
    m_GetConnectionUnixProcessID : (int32 OBus_context.t -> 'a -> string -> int32 Lwt.t) ->
    m_GetAdtAuditSessionData : (string OBus_context.t -> 'a -> string -> string Lwt.t) ->
    m_GetConnectionSELinuxSecurityContext : (string OBus_context.t -> 'a -> string -> string Lwt.t) ->
    m_ReloadConfig : (unit OBus_context.t -> 'a -> unit -> unit Lwt.t) ->
    m_GetId : (string OBus_context.t -> 'a -> unit -> string Lwt.t) ->
    unit -> 'a OBus_object.interface
end
