(* File auto-generated by obus_gen_interface.best, DO NOT EDIT. *)
open OBus_value
open OBus_value.C
open OBus_member
open OBus_object
module Org_freedesktop_PolicyKit_AuthenticationAgent =
struct
  let interface = "org.freedesktop.PolicyKit.AuthenticationAgent"
  let m_ObtainAuthorization = {
    Method.interface = interface;
    Method.member = "ObtainAuthorization";
    Method.i_args = (arg3
                       (Some "action_id", basic_string)
                       (Some "xid", basic_uint32)
                       (Some "pid", basic_uint32));
    Method.o_args = (arg1
                       (Some "gained_authorization", basic_boolean));
  }
  let make
      ?notify_mode
      ~m_ObtainAuthorization:m__ObtainAuthorization
      ()
      =
    OBus_object.make_interface_unsafe ?notify_mode interface
      [|
        method_info m_ObtainAuthorization m__ObtainAuthorization;
      |]
      [|
      |]
      [|
      |]
end
