(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_member

module Org_freedesktop_DBus : sig
  val interface : OBus_name.interface

  type type_start_service_by_name_result = [ `Already_running | `Success ]

  val make_start_service_by_name_result :
    int32 -> type_start_service_by_name_result

  val cast_start_service_by_name_result :
    type_start_service_by_name_result -> int32

  type type_release_name_result = [ `Not_owner | `Non_existent | `Released ]

  val make_release_name_result : int32 -> type_release_name_result

  val cast_release_name_result : type_release_name_result -> int32

  type type_request_name_result =
    [ `Already_owner | `Exists | `In_queue | `Primary_owner ]

  val make_request_name_result : int32 -> type_request_name_result

  val cast_request_name_result : type_request_name_result -> int32

  type type_request_name_flags =
    [ `Do_not_queue | `Replace_existing | `Allow_replacement ]

  val make_request_name_flags : int32 -> type_request_name_flags list

  val cast_request_name_flags : type_request_name_flags list -> int32

  val m_AddMatch : (string, unit) Method.t

  val m_GetAdtAuditSessionData : (string, string) Method.t

  val m_GetConnectionSELinuxSecurityContext : (string, string) Method.t

  val m_GetConnectionUnixProcessID : (string, int32) Method.t

  val m_GetConnectionUnixUser : (string, int32) Method.t

  val m_GetId : (unit, string) Method.t

  val m_GetNameOwner : (string, string) Method.t

  val m_Hello : (unit, string) Method.t

  val m_ListActivatableNames : (unit, string list) Method.t

  val m_ListNames : (unit, string list) Method.t

  val m_ListQueuedOwners : (string, string list) Method.t

  val m_NameHasOwner : (string, bool) Method.t

  val m_ReleaseName : (string, int32) Method.t

  val m_ReloadConfig : (unit, unit) Method.t

  val m_RemoveMatch : (string, unit) Method.t

  val m_RequestName : (string * int32, int32) Method.t

  val m_StartServiceByName : (string * int32, int32) Method.t

  val m_UpdateActivationEnvironment : ((string * string) list, unit) Method.t

  val s_NameAcquired : string Signal.t

  val s_NameLost : string Signal.t

  val s_NameOwnerChanged : (string * string * string) Signal.t

  type 'a members = {
    m_AddMatch : 'a OBus_object.t -> string -> unit Lwt.t;
    m_GetAdtAuditSessionData : 'a OBus_object.t -> string -> string Lwt.t;
    m_GetConnectionSELinuxSecurityContext :
      'a OBus_object.t -> string -> string Lwt.t;
    m_GetConnectionUnixProcessID : 'a OBus_object.t -> string -> int32 Lwt.t;
    m_GetConnectionUnixUser : 'a OBus_object.t -> string -> int32 Lwt.t;
    m_GetId : 'a OBus_object.t -> unit -> string Lwt.t;
    m_GetNameOwner : 'a OBus_object.t -> string -> string Lwt.t;
    m_Hello : 'a OBus_object.t -> unit -> string Lwt.t;
    m_ListActivatableNames : 'a OBus_object.t -> unit -> string list Lwt.t;
    m_ListNames : 'a OBus_object.t -> unit -> string list Lwt.t;
    m_ListQueuedOwners : 'a OBus_object.t -> string -> string list Lwt.t;
    m_NameHasOwner : 'a OBus_object.t -> string -> bool Lwt.t;
    m_ReleaseName : 'a OBus_object.t -> string -> int32 Lwt.t;
    m_ReloadConfig : 'a OBus_object.t -> unit -> unit Lwt.t;
    m_RemoveMatch : 'a OBus_object.t -> string -> unit Lwt.t;
    m_RequestName : 'a OBus_object.t -> string * int32 -> int32 Lwt.t;
    m_StartServiceByName : 'a OBus_object.t -> string * int32 -> int32 Lwt.t;
    m_UpdateActivationEnvironment :
      'a OBus_object.t -> (string * string) list -> unit Lwt.t;
  }

  val make : 'a members -> 'a OBus_object.interface
end

module Org_freedesktop_DBus_Introspectable : sig
  val interface : OBus_name.interface

  val m_Introspect : (unit, string) Method.t

  type 'a members = { m_Introspect : 'a OBus_object.t -> unit -> string Lwt.t }

  val make : 'a members -> 'a OBus_object.interface
end

module Org_freedesktop_DBus_Peer : sig
  val interface : OBus_name.interface

  val m_GetMachineId : (unit, string) Method.t

  val m_Ping : (unit, unit) Method.t

  type 'a members = {
    m_GetMachineId : 'a OBus_object.t -> unit -> string Lwt.t;
    m_Ping : 'a OBus_object.t -> unit -> unit Lwt.t;
  }

  val make : 'a members -> 'a OBus_object.interface
end

module Org_freedesktop_DBus_Properties : sig
  val interface : OBus_name.interface

  val m_Get : (string * string, OBus_value.V.single) Method.t

  val m_GetAll : (string, (string * OBus_value.V.single) list) Method.t

  val m_Set : (string * string * OBus_value.V.single, unit) Method.t

  val s_PropertiesChanged :
    (string * (string * OBus_value.V.single) list * string list) Signal.t

  type 'a members = {
    m_Get : 'a OBus_object.t -> string * string -> OBus_value.V.single Lwt.t;
    m_GetAll :
      'a OBus_object.t -> string -> (string * OBus_value.V.single) list Lwt.t;
    m_Set :
      'a OBus_object.t -> string * string * OBus_value.V.single -> unit Lwt.t;
  }

  val make : 'a members -> 'a OBus_object.interface
end
